sudo: false

language: cpp

cache:
  ccache: true
  diretories:
    - $HOME/.local/conda

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
          - bash-completion
          - curl

    - os: osx
      compiler: clang

install:
  - bash $TRAVIS_BUILD_DIR/build_scripts/travis-install.sh

script:
  - bash $TRAVIS_BUILD_DIR/build_scripts/travis-script.sh
